#!/bin/bash
#
# This script runs the image generated by the docker build script
# using docker run command, where:
#   --rm  automatically removes the container and on exit
#   -i  keeps the standard input open
#   -t  provides a terminal as a interactive shell within container
#   --volumes  are file systems mounted on docker container to preserve
# data generated during the yocto build and these are stored on the host.
# Left side being an absolute path on the host machine, right side being
# an absolute path inside the container.
#
#   $ ./docker-run.sh
#
set +e
# source the common variables
. env.sh

echo "Docker workdir: ${DOCKER_WORKDIR}"

# run the docker image
docker run -it --rm \
    --volume "${HOME}":"${HOME}" \
    --volume "${DOCKER_WORKDIR}":"${DOCKER_WORKDIR}" \
    --volume "${SSTATE_DIR}":"${SSTATE_DIR}" \
    --volume "${DL_DIR}":"${DL_DIR}" \
    "${DOCKER_IMAGE_TAG}" \
    "/bin/bash"
